### ISSUE TITLE
Wrong Checksum

### ISSUE THREAD

**Issue by Wal-demar** [ctc/re_programmer#2]
Hello everyone
first thanks for nice app. Ist only one for programming EnOcean modules.
i have issues with re_programmer and need your help please.
I try to write FW to my STM300 but i get exception.
The FW is from EnOcean webpage [Link](https://www.enocean.com/en/download/firmware-hex-files-updates-868-315-902-mhz/STM300-hwSTM300_platforms_2_2_0_0.zip/)
stm300-868mhz-3dbm-1v54-db_cfg.hex
stm300-868mhz-3dbm-1v54-db.hex
After write 11kb i get exception that the checksum is wrong. 
I uncomment the text out in the Send function:

..............
send11212: 12 05 36 02
send11216: 05 04 A2 14
send11220: 22 FF FF FF
send11224: FF FF FF FF
send11228: FF FF FF FF
send11232: FF FF FF FF
send11236: FF FF FF FF
send11240: FF FF FF FF
send11244: FF FF FF FF
send11248: FF FF FF FF
send11252: FF FF FF FF
send1125Wrote: 11 KBFF
send11260: FF FF FF C1
Traceback (most recent call last):
  File "./re_programmer1.py", line 446, in <module>
    Main()
  File "./re_programmer1.py", line 71, in Main
    WriteProgArea( new_program, program_size)
  File "./re_programmer1.py", line 333, in WriteProgArea
    InfoOk( data, 'WriteProgArea')
  File "./re_programmer1.py", line 303, in InfoOk
    raise Exception( caller + ": wrong chksum: should: " + List2Hex( [data[7]]) + " is: " + List2Hex( [CalcChecksum( data)]))
Exception: WriteProgArea: wrong chksum: should: 00 is: 03

end of hex file 

.............
:102B9000121BA580F37E277FBE1229467F010229E2
:102BA000653EFEE0FCA3E02FFFEC3EFE2243E7047F
:102BB00043E70143E40822EF6003D2A822C2A8221F
:102BC000120493EE8FF00203EB90A0401205360240
:052BD0000504A214221F
:012BFF00C114
:00000001FF

**Comment by Wal-demar** [comment]
The change SPI-Clock from 2MHz to 1MHz solved the problem

**Comment by ctc** [comment]
Program cable layout and length influences the maximum program speed
